version: '3.9'

services:
  web:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./html:/usr/share/nginx/html

  db:
    image: sqlite3:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_database
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
